language: go

go:
  - 1.8.x
  - 1.9.x
  - master

services:
  - docker

env:
  - ROCHEFORT_TEST=http://localhost:4500

before_install:
  - docker pull jackdoe/rochefort:0.5
  - docker run -d -p 127.0.0.1:4500:4500 jackdoe/rochefort:0.5

script: go test ./...
