language: go

go:
  - 1.8.x
  - 1.9.x
  - master

services:
  - docker

env:
  - ROCHEFORT_TEST=http://localhost:8000

before_install:
  - docker pull jackdoe/rochefort:2.2
  - docker run -d -p 127.0.0.1:8000:8000 jackdoe/rochefort:2.2

script: go test ./...
